name: Upload PR Description to Jira

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  upload_to_jira:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR description and upload to Jira
        id: upload_jira_description
        uses: ../actions/upload-jira-comment
        with:
          pull_request: ${{ toJSON(github.event.pull_request) }}
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Log Jira Upload Status
        if: steps.upload_jira_description.outputs.jira_comment_uploaded == 'true'
        run: echo "Successfully uploaded PR description to Jira."

      - name: Log Jira Upload Failure
        if: steps.upload_jira_description.outputs.jira_comment_uploaded == 'false'
        run: echo "Failed to upload PR description to Jira."